name: Docker Image CI

on:
  push:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git
        uses: actions/checkout@v2
      - name: Set version
        id: version
        run: echo ::set-output name=release_version::${GITHUB_REF#refs/*/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (Version)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rudealts/discordbot:${{ steps.version.outputs.release_version }}
      - name: Build and push (Latest)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rudealts/discordbot:latest
